name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: './PeriodicTableNET'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/PeriodicTableNET.sln

    - name: Build solution
      run: dotnet build ${{ env.PROJECT_PATH }}/PeriodicTableNET.sln --configuration Release --no-restore

    - name: Test data library
      run: dotnet test ${{ env.PROJECT_PATH }}/PeriodicTableData/PeriodicTableData.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true  # Allow CI to pass even if no tests exist yet

  validate-android:
    name: Validate Android Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/PeriodicTableMaui/PeriodicTableMaui.csproj

    - name: Build Android (MAUI Controls)
      run: dotnet build ${{ env.PROJECT_PATH }}/PeriodicTableMaui/PeriodicTableMaui.csproj --configuration Release --framework net9.0-android --no-restore

    - name: Build Android (Blazor Hybrid)
      run: dotnet build ${{ env.PROJECT_PATH }}/PeriodicTableBlazorMaui/PeriodicTableBlazorMaui.csproj --configuration Release --framework net9.0-android --no-restore

  validate-windows:
    name: Validate Windows Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/PeriodicTableMaui/PeriodicTableMaui.csproj

    - name: Build Windows (MAUI Controls)
      run: dotnet build ${{ env.PROJECT_PATH }}/PeriodicTableMaui/PeriodicTableMaui.csproj --configuration Release --framework net9.0-windows10.0.19041.0 --no-restore

    - name: Build Windows (Blazor Hybrid)
      run: dotnet build ${{ env.PROJECT_PATH }}/PeriodicTableBlazorMaui/PeriodicTableBlazorMaui.csproj --configuration Release --framework net9.0-windows10.0.19041.0 --no-restore